services:
  frontend:
    build:
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
  nginx:
    image: nginx
    volumes: 
     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 8080:8080