services:
  fastapi:
    image: fastapi
    build: 
      context: ./server 
      dockerfile: Dockerfile
    restart: always
    ports: 
      - 8000:8000

  mongo:
    image: mongo
    ports:
     - 27017:27017

  nginx:
    image: nginx
    volumes: 
     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - fastapi

